name: Build

on:
  push:
    branches:
      - main

env:
  BUILD_COMMAND: gcc -v darwin/src/sqlcmd.c -o darwin/build/sqlcmd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: ${{env.BUILD_COMMAND}}